version: '3.1'

services:
  app:
    image: 'f9dfb509985a'
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
  db:
    image: 'postgres:13.1-alpine'
    expose:
      - '5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
